namespace Facturacion.Domain;

public enum ParametrosEnum
{
    MENSAJES_SERVICIO = 1,
    EVENTOS_SIGNIFICATIVOS = 2,
    MOTIVO_ANULACION = 3,
    PAIS_ORIGEN = 4,
    TIPO_DOCUMENTO_IDENTIDAD = 5,
    TIPO_DOCUMENTO_SECTOR = 6,
    TIPO_EMISION = 7,
    TIPO_HABITACION = 8, 
    TIPO_METODO_PAGO = 9,
    TIPO_MONEDA = 10,
    TIPO_PUNTO_VENTA = 11,
    TIPOS_FACTURA = 12,
    UNIDAD_MEDIDA = 13
}
